tasks:

  # Text counts and sentiment analysis
  nlp:
    type: python
    class: nlp.LanguageProcessing
    parents:
      - message_reply_time
    parameters:
      table: message_reply_time
      text:
        - content

  # Generates wordcloud GIFs for every folder in messenger_data
  # The stopwords parameter adds additional stopwords to our task
  wordcloud:
    type: python
    class: wordcloud.RenderCloud
    parents:
      - message_reply_time
    parameters:
      table: message_reply_time
      facebook_name: 'Vegeta' # Your name on facebook
      stopwords:
        - PLACEHOLDER

  # Requires ImageMagick, link: https://imagemagick.org/
  link_chart_race:
    type: python
    class: link_chart_race.ChartRace
    parents:
      - frequent_sites
    parameters:
      table: frequent_sites
      fixed: False
