tasks:

  message_category_correction:
    preset: modelling
    parents:
      - load_chat_data

  sticker_counts:
    preset: modelling
    parents:
      - load_chat_data

  youtube_links:
    preset: modelling
    parents:
      - load_chat_data
